# Generated by Django 4.0 on 2022-01-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_orderitem_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='storage',
        ),
    ]
